name: Deploy Dev Environment
on:
  push:
    branches:
      - dev

env:
  AWS_REGION: eu-west-2
  COVERAGE_PATH: ./coverage

permissions:
  contents: read

jobs:
  check_migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Look for merge commits in the PR branch
        run: |
          if grep -rnw './src/database/migrations' -e 'local'; then
            echo 'Your migration contains the local stage rather than the stage from the env';
            exit 1;
          fi
  lint:
    runs-on: ubuntu-latest
    needs: [check_migrations]
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v3
      - name: Install Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run lint checker
        run: yarn lint:check
  unit_tests:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v3
      - name: Install Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run unit tests (w/ coverage)
        run: yarn test --watchAll=false --runInBand --coverage  --coverageThreshold '{}'
      - name: Store job's coverage
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: ./coverage
      - name: store_test_results
        uses: actions/upload-artifact@v3
        with:
          name: store_test_results
          path: ./junit/unit

  deploy:
    runs-on: ubuntu-latest
    needs: [unit_tests]
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: yarn
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Compile TypeScript
        run: yarn build
      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Print Serverless environment deployment plan
        run: yarn sls:print --stage dev
      - name: Deploy Serverless deployment plan to environment
        run: yarn sls:deploy --stage dev
